name: Deploy to GOV.UK PaaS

on:
  push:
    branches:
      - main

jobs:
  deploy-to-paas:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Academy transfers
        uses: DFE-Digital/github-actions/setup-cf-cli@master
        with:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_SPACE_NAME: academy-transfers # required

      - name: Push to GOV.UK PaaS
        run: cf push -b staticfile_buildpack academy-transfers-prototype
